
REM executeable DatabaseOfTranslationTables TranslationTable(instructions) PGDBFullPathName

W:\Model_Programs\GISTranslator\TableDrivenTranslator\bin\TableDrivenTranslator.exe TranslationTables.mdb Translate_DJCENG D:\projects\7901_Data_Management\links_nodesPGDB.mdb