
REM executeable DatabaseOfTranslationTables TranslationTable(instructions) PGDBFullPathName

W:\Model_Programs\GISTranslator\TableDrivenTranslator\bin\TableDrivenTranslator.exe TranslationTables.mdb Translate_DEA W:\AGMaster21\SWtrade.mdb